<?php 
global $wpdb; 
$tab = isset($_GET['tab']) ? $_GET['tab']:'info';
$start = microtime(true);
?>
<div class='wrap dev-bar-admin'>
	<h2><i class='fa fa-info'></i> System Information - <span><?php echo $tab?></span></h2>
	<?php 
		$tabs = array(
			'Info'				=>	array('info',		'fa fa-tachometer'),				
			'MySQL Info'		=>	array('mysql_info',	'fa fa-database'),		
			'MySQL Performance'	=>	array('mysql_perf',	'fa fa-database'),		
			'Database'			=>	array('db',			'fa fa-database'),		
			'Permissions'		=>	array('perm',		'fa fa-lock'),		
			'Procs'				=>	array('procs',		'fa fa-cogs'),				
			'Services'			=>	array('services',	'fa fa-crosshairs'),			
			'Open Ports'		=>	array('ports',		'fa fa-bullseye'),			
			'Rewrite Rules'		=>	array('rewrite',	'fa fa-list'),				
			'Cron'				=>	array('cron',		'fa fa-clock-o'),				
			'DNS'				=>	array('dns',		'fa fa-info'),					
			'Whois'				=>	array('whois',		'fa fa-info-circle'),				
			'Error Log'			=>	array('errors',		'fa fa-exclamation-triangle'),		
			#'Tools'				=>	array('tools',		'fa fa-wrench'),		
			'Hooks'				=>	array('hooks',		'fa fa-anchor'),		
			'Functions'			=>	array('functions',	'fa fa-flag'),		
			'WP Options'		=>	array('options',	'fa fa-sliders')		
		);
		
		if( !System_Info_Tools::exec_enabled()){
			unset($tabs['Open Ports']);
			unset($tabs['Procs']);
			unset($tabs['Services']);
		}
		//fsockopen if not remove whois
		
	?>
	<div class="nav-tab-wrapper">
		<?php 
			foreach($tabs as $name => list($param,$icon)){
				#list($param,$icon) = $data;
				$class = ($param==$tab) ? 'nav-tab-active':'';
				echo "<a class=\"nav-tab {$class}\" href=/wp-admin/admin.php?page=sys_info&tab={$param}>
					<i class='{$icon}'></i>
					{$name}
				</a>";
			}
		?>			
	</div>
	<div class='container <?php echo $tab?>'>
		<?php 			
			switch($tab){
				case 'info': 			include(__DIR__.'/tabs/Info.phtml'); break;
				case 'db':				include(__DIR__.'/tabs/DB_Info.phtml'); break;
				case 'perm': 			include(__DIR__.'/tabs/Permissions.phtml'); break;
				case 'procs': 			include(__DIR__.'/tabs/Procs.phtml'); break;
				case 'rewrite': 		include(__DIR__.'/tabs/Rewrites.phtml'); break;
				case 'cron': 			include(__DIR__.'/tabs/Cron.phtml'); break;
				case 'hooks': 			include(__DIR__.'/tabs/Hooks.phtml'); break;
				case 'dns': 			include(__DIR__.'/tabs/DNS.phtml'); break;
				case 'whois': 			include(__DIR__.'/tabs/Whois.phtml'); break;
				case 'errors': 			include(__DIR__.'/tabs/Errors.phtml'); break;
				#case 'tools': 			include(__DIR__.'/tabs/Tools.phtml'); break;
				case 'shell': 			include(__DIR__.'/tabs/Shell.phtml'); break;
				case 'functions': 		include(__DIR__.'/tabs/Functions.phtml'); break;
				case 'mysql_info':		include(__DIR__.'/tabs/DB_Info.phtml'); break;
				case 'mysql_perf':		include(__DIR__.'/tabs/Tab_Mysql_Perf.phtml'); ;break;
				case 'services':		System_Info_Admin::page_services(); break;
				case 'ports':			include(__DIR__.'/../views/admin/tabs/Ports.phtml'); break;
				case 'options': 		include('Tab_Options.phtml'); break;
				case 'about':			include(__DIR__.'/../views/admin/about.phtml'); break;
				default: echo "No such Tab '{$tab}'"; break;			
			}		
			$total = microtime(true) - $start;
			echo "<h4>Total Time - ".number_format($total*1000,2)."ms</h4>";
		?>
	</div>
</div>
