<?php 
global $_wp_additional_image_sizes, $wpdb, $wp_version; 

$have_query_cache = System_Info_SQL::option('have_query_cache');
$query_cache_size = System_Info_SQL::option('query_cache_size');

?>

<?php #global $wp_scripts; var_dump($wp_scripts); ?>
<?php #global $wp_styles; var_dump($wp_styles); ?>

<h3>Speed</h3>
<table class=widefat>
	<tr><th>OpCode Cache</th><td>
		<?php if( extension_loaded( 'xcache' ) ) : ?>XCache
		<?php elseif( extension_loaded( 'apc' ) ) : ?>APC
		<?php elseif( extension_loaded( 'eaccelerator' ) ) : ?>EAccelerator
		<?php elseif( extension_loaded( 'Zend Optimizer+' ) ) : ?>Zend Optimizer+
		<?php elseif( extension_loaded( 'wincache' ) ) : ?>WinCache
		<?php else: ?>None
		<?php endif; ?>
	</td></tr>
	
	<tr><th>Redis</th><td>
	</td></tr>
	<?php if(function_exists('apache_get_modules') ) : $modules = apache_get_modules();  ?>
		<tr><th>Apache Modules</th><td>
			<?php echo print_r($modules); ?>
		</td></tr>	
	<?php endif; ?>
	<tr><th>Memory Limit
	<tr><th>APC Cache Limit
	
	<tr><th>MySQL Cache</th><td></td></tr>
	
	<tr><th>Query Cache</th><td><?php echo $have_query_cache ?></td></tr>
	<tr><th>Cache Size</th><td><?php echo $query_cache_size?></td></tr>
	
</table>

<table class='wp-list-table widefat fixed server_info'>
	<tr><th colspan=2 class=hdr>Software
	<tr><th>OS<td><?php echo System_Info_Tools::color_format(php_uname())?>
	<tr><th>PHP Version<td><?php echo PHP_VERSION?>
	<tr><th>MySQL Version<td><?php echo System_Info_Tools::color_format($wpdb->db_version()); ?>
	<tr><th>Webserver<td><?php echo System_Info_Tools::color_format($_SERVER['SERVER_SOFTWARE'])?>
	<tr><th>Webserver User<td><?php echo (System_Info_Tools::is_windows()) ? get_current_user():exec('whoami');?></tr>
	
	<?php if(($_SERVER['SERVER_SOFTWARE']=='Apache') && function_exists('apache_get_modules')) : 
			$modules = apache_get_modules(); ?>	
			<tr><th>Apache Modules</th>
			<td>
				<?php foreach($modules as $m) : ?>
					<span><?php echo $m?></span>
				<?php endforeach; ?>
			</td></tr>
	<?php endif; ?>		
	
	<tr><th colspan=2 class=hdr>Wordpress Info</th></tr>
	<tr><th>Wordpress Version</th><td><?php echo $wp_version?></tr>
	<tr><th>WP_DEBUG</th><td><?php echo System_Info_Tools::color_format((WP_DEBUG)?'Yes':'No')?></tr>
	<tr><th>WP_DEBUG_DISPLAY</th><td><?php echo System_Info_Tools::color_format((WP_DEBUG_DISPLAY)?'Yes':'No')?></tr>
	<tr><th>WP_DEBUG_LOG</th><td><?php echo System_Info_Tools::color_format(WP_DEBUG_LOG)?></td></tr>
	<tr><th>WP_PLUGIN_DIR</th><td><?php echo System_Info_Tools::color_format(WP_PLUGIN_DIR)?></tr>
	<tr><th>FS_METHOD</th><td><?php if (defined('FS_METHOD')) echo System_Info_Tools::color_format(FS_METHOD)?></tr>			
	<tr><th>Post Revisions<td><?php echo (WP_POST_REVISIONS)?'Yes':'No'?></tr>
	<tr><th>Auto Save Interval</th><td><?php echo AUTOSAVE_INTERVAL?></tr>
	<tr><th colspan=2 class=hdr>MySQL Info</th></tr>
	<tr><th>MySQL Query Cache Size</th><td><?php 
		$query_cache = $wpdb->get_row("SHOW VARIABLES LIKE 'query_cache_size'");
		if(!$query_cache)
			echo "<span class=red>Query Cache Not Enabled!</span>";
		else 
			echo System_Info_Tools::formatBytes($query_cache->Value);
	?></td></tr>
	<?php $slow_queries = System_Info_SQL::check_query_log(); ?>
	<tr><th>Slow Query Output</th><td><?php echo $slow_queries->log_output?></td></tr>
	<tr><th>Slow Query Location</th><td><?php echo $slow_queries->slow_query_log?></td></tr>
	<tr><th>Slow Query Not Using Indexes</th><td><?php echo $slow_queries->log_not_using_indexes?></td></tr>
	<tr><th>Database<td><?php echo DB_NAME?>
	<tr><th>User<td><?php echo DB_USER?>
	<tr><th>Host<td><?php echo DB_HOST?>				
	<tr><th colspan=2 class=hdr>Environment Info
	<tr><?php if(!empty($_SERVER['APPLICATION_ENV']) ) : ?>
		<th>Environment<td><?php echo System_Info_Tools::color_format($_SERVER['APPLICATION_ENV'])?>
	<?php endif; ?>
	<tr><th>Server API</th><td><?php echo System_Info_Tools::color_format(PHP_SAPI)?></td></tr>
	<tr><th>Document Root</th><td><?php echo $_SERVER['DOCUMENT_ROOT'];?></th></tr>			
	<?php if(($_SERVER['SERVER_SOFTWARE']=='Apache') && function_exists('apache_get_modules')) : 
			$modules = apache_get_modules(); ?>	
			<tr><th>Apache Modules</th>
			<td>
				<?php foreach($modules as $m) : ?>
					<span><?php echo $m?></span>
				<?php endforeach; ?>
			</td></tr>
	<?php endif; ?>			
</table>

<h3>Image Sizes</h3>
<table class='widefat'>
	<thead>
		<tr>
			<th>Name</th>
			<th>Width</th>
			<th>Height</th>
			<th>Hard Crop</th>
			<th>Size</th>
	</thead>
	<tbody>
	<?php foreach($_wp_additional_image_sizes as $name=>$i) : ?>
		<tr>
			<td><?php echo $name?></td>
			<td><?php echo $i['width'] ?></td>
			<td><?php echo $i['height']?></td>
			<td><?php echo ($i['crop'])?'Yes':'No'?></td>
			<td><div style='background-color:red;width:<?php echo $i['width']?>px;height:<?php echo $i['height']?>px'></div></td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>


<h2>PHP Settings</h2>
<table class='widefat'>
<tr><th>Loaded Configuration</th><td><?php echo php_ini_loaded_file();?></td></tr>
	<tr><th>Extensions Directory</th><td><?php echo PHP_EXTENSION_DIR?></td></tr>
	<tr><th>max_execution_time</th><td><?php echo ini_get('max_execution_time');?></td></tr>
	<tr><th>post_max_size</th><td><?php echo ini_get('post_max_size');?></td></tr>
	<tr><th>upload_max_filesize</th><td><?php echo ini_get('upload_max_filesize');?></td></tr>
	<tr><th>memory_limit</th><td><?php echo ini_get('memory_limit');?></td></tr>
	<tr><th>open_basedir</th><td><?php echo ini_get('open_basedir');?></td></tr>
	<tr><th>short_open_tag</th><td><?php echo ini_get('short_open_tag');?></td></tr>
	<tr><th>safe_mode</th><td><?php echo ini_get('safe_mode');?></td></tr>		
		<?php if(function_exists('apc_cache_info')) : $info = apc_cache_info(); ?>
			<tr><th>APC</th><td>
			<pre><?php 
				$fields = array(
					'num_slots',       
					'ttl',                 
					'num_hits',            
					'num_misses',          
					'num_inserts',         
					'expunges',            
					'start_time',          
					'mem_size',            
					'num_entries',         
					'file_upload_progress',
					'memory_type',         
					'locking_type',        
				);
				foreach($fields as $f)
					echo "<label></label> {$info[$f]}<br/>";
			?></pre>
		<?php endif; ?></td></tr>
		
		<?php $disabled = ini_get('disable_functions'); ?>
		<tr><th>Disabled Functions</th><td>
		<?php if(!empty($disabled)) :?> 
		<?php foreach($disabled as $d) : ?>
			<?php echo $d?> is Disabled 
		<?php endforeach; ?>
		<?php else: ?>
			None
		<?php endif; ?>
		</td></tr>
		<tr><th>PHP Extensions</th>
		<td>
			<ul class=threecol>		
			<?php $extensions = get_loaded_extensions(); ?>
			<?php foreach($extensions as $e): ?>
				<li><a href=http://www.php.net/manual/en/book.<?php echo strtolower($e)?>.php><?php echo $e?></a></li>		
			<?php endforeach; ?>
			</ul> 	
		</td>
		</tr>
</table>				
		
