<?php 
	$procs = System_Info_Tools::running_procs(); 						
?>
<table class='wp-list-table widefat fixed proc_table datatable'>
	<thead>
		<tr>			
			<?php foreach($keys as $h): ?>
				<th><?php echo $h?></th>
			<?php endforeach; ?>			
		</tr>
	</thead>
	<tbody>
		<?php foreach($procs as $p) : ?>
			<tr>
				<?php foreach($p as $d) : ?>
					<td><?php echo System_Info_Tools::color_format($d)?></td>
				<?php endforeach; ?>
			</tr>
		<?php endforeach; ?>
	<tbody>
</table>