<?php 
$cron = _get_cron_array();
?>
<table class='wp-list-table widefat fixed'>
	<thead><tr><th>ID</th><th>Name</th><th>args</th><th>Schedule</th></tr>
<?php 
	foreach($cron as $arr){ 
		foreach($arr as $name=>$c){ 	
			foreach($c as $job){
			?><tr>
				<td class=cGreen><?php echo $name?></td>
				<td class=cPurple><?php echo $job['schedule']?></td>
				<td><?php 
					if( empty( $job['args'] ) ){
						echo "Empty";
					}
					else{
						echo "<div class=wpcron_job>";
						foreach($job['args'] as $k=>$j){
							if( is_array($k) ){ 
								foreach($k as $l=>$r){
									?>
									<h3>!!<?php echo $l?></h3>
									<div><?php echo print_r($r, true);?></div>
									<?
								}
							}								
							else{
								?>
									<h3>@<?php echo $k?></h3>
									<div><?php echo print_r($j, true);?></div>
								<?
							}
							echo "</div>";
						}						
					?>
					</td>
					<td><?php echo $job['interval']?></td>
<?php 			}
			}#$c as $job
		} #arr as $name=>$c
	}#cron as $ar
?>
</table>
<?php if( System_Info_Tools::is_windows() ) : ?>
	<h3>Scheduled Tasks</h3>
	<?php 
		$xmlString = System_Info_Tools::run_command(exec('schtasks /query /XML'));
		$xml = simplexml_load_string($xmlString);
		d( $xmlString );
	?>
<?php else: ?>
	<h3>Crontab</h3>
	<?php
		$out = System_Info_Tools::run_command("/usr/bin/crontab -l");
		echo "<pre>".print_r($out,true)."</pre>";
	?>
<?php endif; ?>