<table class='wp-list-table widefat fixed'>
					<thead>
						<tr>
							<th>Name</th>
							<th>Type</th>
							<th>Permissions</th>
							<th>User</th>
							<th>Group</th>
							<th>World</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach(self::permissions() as $p) : ?>
							<?php 
								$perms = $p['permissions'];
								if (($perms & 0xC000) == 0xC000) 		$type = 'socket'; // Socket
								elseif (($perms & 0xA000) == 0xA000) 	$type = 'symlink'; // Symbolic Link
								elseif (($perms & 0x8000) == 0x8000)	$type = 'regular file'; // Regular
								elseif (($perms & 0x6000) == 0x6000)	$type = 'block';// Block special
								elseif (($perms & 0x4000) == 0x4000)	$type = 'directory';// Directory
								elseif (($perms & 0x2000) == 0x2000) 	$type = 'character';// Character special
								elseif (($perms & 0x1000) == 0x1000) 	$type = 'pipe';// FIFO pipe
								else 									$type = 'unkown';// Unknown
								
								#User
								$user = (($perms & 0x0100) ? 'r' : '-');
								$user .= (($perms & 0x0080) ? 'w' : '-');
								$user .= (($perms & 0x0040) ? (($perms & 0x0800) ? 's' : 'x' ) : (($perms & 0x0800) ? 'S' : '-'));
								#Group
								$group = (($perms & 0x0020) ? 'r' : '-');
								$group .= (($perms & 0x0010) ? 'w' : '-');
								$group .= (($perms & 0x0008) ? (($perms & 0x0400) ? 's' : 'x' ) : (($perms & 0x0400) ? 'S' : '-'));
								#World
								$world = (($perms & 0x0004) ? 'r' : '-');
								$world .= (($perms & 0x0002) ? 'w' : '-');
								$world .= (($perms & 0x0001) ? (($perms & 0x0200) ? 't' : 'x' ) : (($perms & 0x0200) ? 'T' : '-'));
							?>
							<tr>
								<th class=cBlue><?php echo $p['path']?></th>
								<td class=cPurple><?php echo $type?></td>
								<th class=cOrange><?php echo substr(sprintf('%o', $p['permissions']), -4);?></th>
								<td class=cRed><?php echo $user?></td>
								<td class=cRed><?php echo $group?></td>
								<td class=cRed><?php echo $world?></td>
							</tr>
						<?php endforeach; ?>
					</tbody>
					</table>
					<?php 
					$user = (System_Info_Tools::is_windows()) ? get_current_user():exec('whoami');
					?>
					chmod -R 755
					chown -R <?php echo $user?>:{$group} <?php echo WP_CONTENT_DIR?>					
		<?