<?php
if( System_Info_Tools::is_windows() ){			
			$cmd = 'netstat -ano | find "LISTENING"';
			$out = System_Info_Tools::run_command( $cmd );
			$out = preg_replace('!\s+!', ' ', $out);
			$out = str_replace(' ',',',$out);
			$out = System_Info_Tools::read_csv_array( $out,",");
			foreach($out as $k=>$o){
				unset($out[$k][0]);
			}
			System_Info_Tools::out_table($out);
		}
		else{
			$out = System_Info_Tools::run_command('netstat -tulpn');
			echo "<pre>";
			echo implode("\r\n",$out);
			echo "</pre>";
		}