<?php
global $wpdb,$post,$wp_filter,$timestart,$wp_object_cache,$dbg_filter_calls,$SI_Errors;

#calculate debug time, Server Side and JS/DOM side
$start_debug 	= microtime(true); 
$tpl_dir 		= get_template_directory();

$total_query_time=0;
foreach($wpdb->queries as $q){
	$total_query_time+= $q[1];
}
	
$total_query_time_ms 	= number_format($total_query_time*1000,2);
$time_taken 			= microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'];
$query_percentage 		= number_format(($total_query_time/$time_taken) * 100,2); //Backwards?
$query_details 			= (empty($wpdb->queries)) ? $wpdb->num_queries:"{$wpdb->num_queries} in {$total_query_time_ms}ms";

$files 					= get_included_files();
$included_file_count 	= count($files);

$total_filter_duration 	= array_sum($GLOBALS['dbg_filter_times']);
$filter_details 		= number_format($total_filter_duration*1000,2)."ms";

$error_count = count($SI_Errors);
include('bar.php');

?>	
<div id=dbg_bar>
	<div id=debug-bar-resize></div>
	<ul class=tabs>
		<li class=current><a href=#dbg_info><i class=fa-info></i> Info</a></li>
		<li><a href=#dbg_errors><i class=fa-warning></i> Errors <small class=bdg><?php echo $error_count?></small></a></li>
		<li><a href=#dbg_db><i class=fa-database></i> Queries <small class=bdg><?php echo $query_details;?></small></a></li>
		<li><a href=#dbg_filters><i class=fa-filter></i> Filters <small class=bdg><?php echo $filter_details;?></small></a></li>		
		<li><a href=#dbg_files><i class=fa-file></i> Included Files <span class=bdg><?php echo $included_file_count?></span></a></li>
		
		<li><a href=#dbg_system><i class=fa-info></i> System</a></li>
		<li><a href=#dbg_globals><i class=fa-globe></i> Globals</a></li>
		<?php if(!empty($_SERVER)) 		: ?><li><a href=#dbg_server><i class=fa-desktop></i> Server</a></li><?php endif; ?>
		<?php if(!empty($_COOKIE)) 		: ?><li><a href=#dbg_cookies><i class=fa-info></i> Cookies</a></li><?php endif; ?>
		<?php if(!empty($_SESSION)) 	: ?><li><a href=#dbg_session><i class=fa-info></i> Session</a></li><?php endif; ?>
		<?php if(!empty($_ENV)) 		: ?><li><a href=#dbg_env><i class=fa-info></i> Env</a></li><?php endif; ?>						
		<?php if(!empty($_REQUEST)) 	: ?><li><a href=#dbg_request><i class=fa-info></i> Request</a></li><?php endif; ?>							
		
		<li><a href=#dbg_cache><i class=fa-info></i> Cache</a></li>				
		<li><a href=#dbg_timeline><i class=fa-clock-o></i> Timeline</a></li>				
		
		<li class=right id=close_dbg><i class=fa-times></i></li>
		<li class=right><i class=mem></i><?php echo number_format(memory_get_usage()/1024,0) ?>KB</li>
		<li class=right><i class=time></i><?php echo number_format($time_taken,2) ?>ms</li>		
	</ul>
<div class=dbg_body>
	<div class='panel active' id=dbg_info><?php include('info.phtml');?></div>
	<div class=panel id=dbg_cache><?php 	include('cache.phtml'); ?></div>
	<div class=panel id=dbg_globals><?php 	include('globals.phtml');?></div>
	<div class=panel id=dbg_files><?php 	include('included_files.phtml'); ?></div>
	<div class=panel id=dbg_filters><?php include('filters.phtml');?></div>
	<div class=panel id=dbg_timeline><?php include('frontend.phtml'); ?></div>
	<div class=panel id=dbg_system><?php include('system.phtml');?></div>
	<div class=panel id=dbg_php><?php include('php.phtml');?></div>
	<div class=panel id=dbg_db><?php include('db.phtml')?></div>
	<?php if(!empty($_SERVER)) 		: ?><div class=panel id=dbg_server>	<h3>Server</h3>		<?php 	dbg_table_out($_SERVER); 	?></div><?php endif; ?>
	<?php if(!empty($_COOKIE)) 		: ?><div class=panel id=dbg_cookies><h3>Cookie</h3>		<?php	dbg_table_out($_COOKIE); 	?></div><?php endif; ?>
	<?php if(!empty($_SESSION)) 	: ?><div class=panel id=dbg_session><h3>Session</h3>	<?php	dbg_table_out($_SESSION);	?></div><?php endif; ?>
	<?php if(!empty($_ENV)) 		: ?><div class=panel id=dbg_env>	<h3>ENV</h3>		<?php	dbg_table_out($_ENV);		?></div><?php endif; ?>
	<?php if(!empty($_REQUEST)) 	: ?><div class=panel id=dbg_request><h3>Request</h3>	<?php	dbg_table_out($_REQUEST);	?></div><?php endif; ?>
	<div class=panel id=dbg_errors><?php 	include('errors.phtml');?></div>
</div>


<script>
<?php $debug_time = microtime(true) - $start_debug;?>
var debug_time = <?php echo number_format($debug_time,2);?>;
</script>