<?php
global $wpdb,$wp_version;
		
		
	#$_SERVER['NUMBER_OF_PROCESSORS']	#Defined on Windows
/*
Local IP
APC Enabled	
*/
$start = microtime(true);		

try{		
	$mem = memory_get_usage();

	$free_disk_bytes 	= disk_free_space( $_SERVER['DOCUMENT_ROOT'] );
	$total_disk_bytes 	= disk_total_space( $_SERVER['DOCUMENT_ROOT'] );

	$free_disk 	= System_Info_Tools::formatBytes($free_disk_bytes);
	$total_disk = System_Info_Tools::formatBytes($total_disk_bytes);

	$used_disk 	= $total_disk_bytes - $free_disk_bytes;

	$perc_used = number_format($used_disk * 100 / $total_disk_bytes,2);

	if(strtoupper(substr(PHP_OS, 0, 3)) === 'WIN'){
		//Windows
		exec("net statistics workstation | find 'Statistics since'", $uptime);
	}
	else{
		exec('uptime', $uptime);
		//Assume Linux, check if can exec
		if( function_exists('exec') ){
			exec('cat /proc/meminfo', $mem_info);
			exec('cat /proc/cpuinfo',	$cpu_info);
			
			$mem_info_details = [];
			foreach($mem_info as $mi){
				if(!empty($mi)){
					list($prop,$val) = explode(':',$mi,2);
					$mem_info_details[trim($prop)] = trim($val);
				}
			}
			$cpu_info_details = [];
			foreach($cpu_info as $mi){
				if(!empty($mi)){
					list($prop,$val) = explode(':',$mi,2);						
					$cpu_info_details[trim($prop)] = trim($val);
				}
			}
		}
	}

	if( function_exists('sys_getloadavg') ){
		$load_avg = sys_getloadavg();
	}

	$mem_usage = round( memory_get_usage() / 1024 / 1024, 2 );

	$db_size = $wpdb->get_row($wpdb->prepare("SELECT table_schema,
			SUM( data_length + index_length ) AS `Size`,
			SUM( data_free ) AS  `Free`
			FROM information_schema.TABLES
			WHERE table_schema = %s
			GROUP BY table_schema",DB_NAME));
	
	$db_used = System_Info_Tools::formatBytes($db_size->Size);
	$db_free = System_Info_Tools::formatBytes($db_size->Free); 

	$theme = wp_get_theme();
}catch(Exception $e){
	echo "<h2>Error Getting System Information</h2>";
}
?>		

<table id=wp_system_info>
	<tr><th colspan=2><h2><i class='dashicons dashicons-desktop'></i> System</h2></th></tr>
	<tr><th>OS</th><td><?=php_uname()?></td></tr>
	<tr><th>IP</th><td><?=$_SERVER['SERVER_ADDR']?></td></tr>
	<tr><th>Webserver</th><td><?=$_SERVER['SERVER_SOFTWARE']?></td></tr>						
	<tr><th colspan=2><h2><i class='dashicons dashicons-admin-generic'></i> PHP</h2></th></tr>
	<tr><th>Version</th><td><?=PHP_VERSION?></td></tr>
	<tr><th>Max Post</th><td><?=ini_get('post_max_size')?></td></tr>
	<tr><th>Upload Max</th><td><?=ini_get('upload_max_filesize')?></td></tr>
	<tr><th>Memory Limit</th><td><?=ini_get('memory_limit')?></td></tr>			
	<tr><th>Max Time</th><td><?=ini_get('max_execution_time')?></td></tr>
	<tr><th colspan=2><h2><i class='dashicons dashicons-chart-pie'></i> Usage</h2></th></tr>

<?php if(!empty($load_avg)) : list($avg1,$avg5,$avg15) = $load_avg; ?>
	<tr>
		<th>Load Avg</th>
		<td>1 Min: <?php echo $avg1?>%<br/>
		5 Min: <?php echo $avg5?>%<br/>
		15Min: <?php echo $avg15?>%
		</td>
	</tr>
<?php endif; ?>

<?php if(!empty($mem_info_details)) : ?>
	<tr><th>Total Memory</th><td><?=$mem_info_details['MemTotal']?></td></tr>
	<tr><th>Free Memory</th><td><?=$mem_info_details['MemFree']?></td></tr>
<?php endif; ?>
<?php if(!empty($cpu_info_details)) : ?>
	<tr><th>CPU</th><td><?php echo $cpu_info_details['model name']?></td></tr>
	<tr><th>MHz</th><td><?php echo $cpu_info_details['cpu MHz']?></td></tr>
	<tr><th>CPU Cache</th><td><?php echo $cpu_info_details['cache size']?></td></tr>
<?php endif; ?>

<tr><th>PHP Memory Usage</th><td><?php echo $mem_usage?></td></tr>
	<tr><th>Disk Space</th><td><?php echo $free_disk?> Free of <?php echo $total_disk?></td></tr>
	<tr><th>Disk Usage</th><td><progress value="<?php echo $perc_used?>" max=100></progress> <?php echo $perc_used?>%</td></tr>
	<tr><th colspan=2><h2><i class='dashicons dashicons-wordpress'></i> Wordpress</h2></th></tr>
	<tr><th>Version</th><td><?php echo $wp_version?></td></tr>			
	<tr><th>Document Root</th><td><?php echo $_SERVER['DOCUMENT_ROOT']?></td></tr>
	<tr><th>Database</th><td><?php echo DB_NAME?></td></tr>
	<tr><th>DB Size</th><td><?php echo "{$db_used}, {$db_free} Free" ?></td></tr>
	<tr><th>Theme</th><td><?php echo $theme->Name?><br/><?php echo $theme->theme_root?></td></tr>
</table>

<?php d( $uptime ); ?>


<pre>
	<?php
	print_r($mem_info_details);
	print_r($cpu_info_details);
	?>
</pre>

<?php 
	$elapsed = number_format(microtime(true) - $start,6);
	echo "<small>Time Taken: {$elapsed}s</small>";
?>