<?php global $wpdb; ?>
<div id=icon-tools class=icon32></div>
		<h2>System Information</h2><br/>
		<script>
		jQuery(document).ready(function() {
			jQuery('#tabs').tabs({
				cache: true,
				load: function(e,ui){
					 jQuery(ui.panel).find(".tab-loading").remove();
				},
				select: function(e,ui){
					 var panel = jQuery(ui.panel);
					 if (panel.is(":empty")) {
						 panel.append("<div class='tab-loading'>Loading...</div>")
					}
				},
				load : function(){
					jQuery('#tabs .datatable').datatable({
						"bPaginate": false,
						 "bJQueryUI": true,
						 'bRetrieve':true
					});
				}
				
			});
		});
		function optimizeTable(table){
			jQuery.ajax({
				url: ajaxurl,
				data:{action:'sysinfo_optimize_table', table:table},
				dataType:'html',
				success:function(h){
					h = '<div>'+h+'</div>';
					jQuery(h).dialog({
						modal: true,
						buttons: { Ok: function() { jQuery( this ).dialog( "close" );}}
					});
				}
			});
		}
		</script>
		<div class='wrap infopage'>		
			<div id=tabs>
				<ul>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=info'>Info</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=phpinfo'>PHP Info</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=mysql_info'>MySQL Info</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=db'>Database</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=perm'>Permissions</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=procs'>Procceses</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=services'>Services</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=ports'>Open Ports</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=rewrite'>Rewrite Rules</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=cron'>Cron</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=dns'>DNS</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=whois'>Whois</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=errors'>Error Log</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=tools'>Tools</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=hooks'>Hooks</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=functions'>Functions</a></li>
					<li><a href='<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php?action=sysinfo&tab=shell'>Shell</a></li>
				</ul>
				<div id=info></div>
				<div id=mysql_info></div>
				<div id=php></div>
				<div id=db></div>
				<div id=perm></div>
				
				<div id=procs></div>
				<div id=services></div>
				<div id=ports></div>
				
				<div id=tools></div>
				<div id=cron></div>
				<div id=hooks></div>
				<div id=dns></div>
				<div id=whois></div>
				
				<div id=rewrite></div>
				<div id=errors></div>
				<div id=functions></div>
				<div id=shell></div>
			</div>
		</div>