<a target=_blank href=http://sitecheck.sucuri.net/results/<?php echo $_SERVER['HTTP_HOST']?>/>Sucuri Sitecheck</a><br/>
		<a target=_blank href=#>Pingdom</a><br/>
		<!--
		http://safebrowsing.clients.google.com/safebrowsing/diagnostic?site=theajcf.org
		http://safeweb.norton.com/report/show?url=theajcf.org
		http://www.siteadvisor.com/sites/theajcf.org
		http://www.yandex.com/infected?url=theajcf.org&l10n=en
		-->
		<a target=_blank href=#>Alexa</a><br/>
		<a target=_blank href=#>Google</a><br/>					
		<form class=postbox>
			
			This can't just work like this.
			It might be serialized data in certain areas like meta
			
			
			<h2>Content Replace</h2>
			<input type=hidden name=action value=sysinfo_replace_content>
			<label>Replace<label><input type=text name=replace><br/>
			<label>With<label><input type=text name=with><br/>
			<button type=button id=replace onClick="replace_content();">Replace</button>
		</form>
		<script>
		function replace_content(){
			$.ajax({
				url: ajaxurl,
				data: jQuery().serialize(),
				success: function(){
					alert('Replaced!');
				}
			});
		}
		</script>