		<h3>WP Cron</h3>
		<table class='wp-list-table widefat fixed'>
			<thead><tr><th>ID</th><th>Name</th><th>args</th><th>Schedule</th></tr>
		<?php 
			foreach($cron as $arr){ 
				foreach($arr as $name=>$c){ 	
					foreach($c as $job){
					?><tr>
						<td><?php echo $name?></td>
						<td><?php echo $job['schedule']?></td>
						<td><?php 
							if( empty( $job['args'] ) ){
								echo "Empty";
							}
							else{
								echo "<div class=wpcron_job>";
								foreach($job['args'] as $k=>$j){
									if( is_array($k) ){ 
										foreach($k as $l=>$r){
											?>
											<h3>!!<?php echo $l?></h3>
											<div><?php echo print_r($r, true);?></div>
											<?
										}
									}								
									else{
										?>
											<h3>@<?php echo $k?></h3>
											<div><?php echo print_r($j, true);?></div>
										<?
									}
									echo "</div>";
								}						
							?>
							</td>
							<td><?php echo $job['interval']?></td>
		<?php 			}
					}#$c as $job
				} #arr as $name=>$c
			}#cron as $ar
		?>
		</table>
		<script>jQuery('.wpcron_jobs').accordion({collapsible: true,allwayOpen: false});</script>
		<h3>crontab</h3>
		<?php
		if( self::is_windows() ){
			$xmlString = self::run_command(exec('schtasks /query /XML'));
			$xml = simplexml_load_string($xmlString);
			print_r( $xmlString );
		}
		else{
			$out = self::run_command("/usr/bin/crontab -l");
			print_r($cout);
		}