<table class=server_info>
			<tr><th colspan=2 class=hdr>Software
			<tr><th>OS<td><?php echo System_Info_Tools::color_format(php_uname())?>
			<tr><th>PHP Version<td><?php echo PHP_VERSION?>
			<tr><th>MySQL Version<td><?php echo System_Info_Tools::color_format($wpdb->db_version()); ?>
			<tr><th>Webserver<td><?php echo System_Info_Tools::color_format($_SERVER['SERVER_SOFTWARE'])?>
			<tr><th>Webserver User<td><?php echo (System_Info_Tools::is_windows()) ? get_current_user():exec('whoami');?></tr>
			<tr><th colspan=2 class=hdr>Wordpress Info</th></tr>
			<tr><th>Wordpress Version</th><td><?php echo $wp_version?></tr>
			<tr><th>WP_DEBUG</th><td><?php echo System_Info_Tools::color_format((WP_DEBUG)?'Yes':'No')?></tr>
			<tr><th>WP_DEBUG_DISPLAY</th><td><?php echo System_Info_Tools::color_format((WP_DEBUG_DISPLAY)?'Yes':'No')?></tr>
			<tr><th>WP_DEBUG_LOG</th><td><?php echo System_Info_Tools::color_format(WP_DEBUG_LOG)?></td></tr>
			<tr><th>WP_PLUGIN_DIR</th><td><?php echo System_Info_Tools::color_format(WP_PLUGIN_DIR)?></tr>
			<tr><th>FS_METHOD</th><td><?php echo System_Info_Tools::color_format(FS_METHOD)?></tr>			
			<tr><th>Post Revisions<td><?php echo (WP_POST_REVISIONS)?'Yes':'No'?></tr>
			<tr><th>Auto Save Interval</th><td><?php echo AUTOSAVE_INTERVAL?></tr>
			<tr><th colspan=2 class=hdr>MySQL Info</th></tr>
			<tr><th>MySQL Query Cache Size</th><td><?php 
				$query_cache = $wpdb->get_row("SHOW VARIABLES LIKE 'query_cache_size'");
				if(!$query_cache)
					echo "<span class=red>Query Cache Not Enabled!</span>";
				else 
					echo System_Info_Tools::formatBytes($query_cache->Value);
			?></td></tr>
			<?php $slow_queries = System_Info_SQL::check_query_log(); ?>
			<tr><th>Slow Query Output</th><td><?php echo $slow_queries->log_output?></td></tr>
			<tr><th>Slow Query Location</th><td><?php echo $slow_queries->slow_query_log?></td></tr>
			<tr><th>Slow Query Not Using Indexes</th><td><?php echo $slow_queries->log_not_using_indexes?></td></tr>
			<tr><th>Database<td><?php echo DB_NAME?>
			<tr><th>User<td><?php echo DB_USER?>
			<tr><th>Host<td><?php echo DB_HOST?>				
			<tr><th colspan=2 class=hdr>Environment Info
			<tr><?php if(!empty($_SERVER['APPLICATION_ENV']) ) : ?>
				<th>Environment<td><?php echo System_Info_Tools::color_format($_SERVER['APPLICATION_ENV'])?>
			<?php endif; ?>
			<tr><th>Server API</th><td><?php echo System_Info_Tools::color_format(PHP_SAPI)?></td></tr>
			<tr><th>Document Root</th><td><?php echo $_SERVER['DOCUMENT_ROOT'];?></th></tr>			
			<?php if(($_SERVER['SERVER_SOFTWARE']=='Apache') && function_exists('apache_get_modules')) : 
					$modules = apache_get_modules(); ?>	
					<tr><th>Apache Modules</th>
					<td>
						<?php foreach($modules as $m) : ?>
							<span><?php echo $m?></span>
						<?php endforeach; ?>
					</td></tr>
			<?php endif; ?>