<h3>DNS Records for <?php echo $host?></h3>
		<table class='wp-list-table widefat fixed'>
			<thead><tr><th>Host<th>Class<th>Type<th><th>TTL</tr></thead>
		<?php foreach($dns as $d) : ?>
			<tr>
				<td><?php echo $d['host']?></td>
				<td><?php echo $d['class']?></td>
				<td><?php echo $d['type']?></td>
				<td><?php 
					if($d['type'] == 'A')
						echo $d['ip'];
					elseif($d['type'] == 'MC')
						echo $d['pri'];
					elseif($d['type'] == 'TXT')
						echo $d['txt'];
				?></td>
				<td><?php echo $d['ttl']?></td>
		<?php endforeach; ?>
		</table>